### ISSUE TITLE
无法获取其他APP的通知

### ISSUE THREAD

**Issue by LanYangYang-114** [AutoAccountingOrg/Qianji_auto#10]
### 当前使用的框架

- [X] Lsposed
- [ ] EdXposed
- [ ] 太极（无极）
- [ ] 轮回
- [ ] 梦境
- [ ] 其他虚拟框架

### 描述错误

无法获取未适配的软件的通知（NotifyMe）

### 重现步骤

```bash
背景说明：我的支付宝安装在主力机，无法解锁BL，也不打算用虚拟框架和无障碍方案，但支付宝和银行APP只能在一台设备上登录，打算使用通知转发的方案将软件的支付成功通知转发到已Root并安装LSPosed的备用机上，以实现对这些软件的自动记账
我的操作步骤：
1、配置好备用机上的NotifyMe，确保其常驻后台和显示通知
2、确认了自动记账拥有通知权限
3、使NotifyMe生成一条测试通知
4、日志中收到了通知，但没有在通知列表显示，也没有被刚创建的通知识别规则识别
```

### 相关环境说明

系统版本：MIUI 13.0.5.0.SGICNXM
安卓版本：12
自动记账版本：3.3.4
NotifyMe版本：3.3.1
通知重要级别从最低到最高都试过了，全部一样

通知截图：
![Screenshot_2024-06-14-15-39-06-657-edit_com wzn55](https://github.com/AutoAccountingOrg/Qianji_auto/assets/84030410/fb19df9c-833a-4c45-8e75-f15c06dff640)
监控APP页面截图：
![Screenshot_2024-06-14-15-37-41-094_cn dreamn qian](https://github.com/AutoAccountingOrg/Qianji_auto/assets/84030410/1268e590-e148-4069-a367-4690c4b2eeff)
通知列表页面截图：
![Screenshot_2024-06-14-15-37-28-758_cn dreamn qian](https://github.com/AutoAccountingOrg/Qianji_auto/assets/84030410/6f683470-8aad-424c-b0ff-ac07cd13c2c4)
规则截图：
![Screenshot_2024-06-14-15-36-24-884_cn dreamn qian](https://github.com/AutoAccountingOrg/Qianji_auto/assets/84030410/0b9844f5-b851-4d1f-838f-2ebf7b492e8a)
按下规则测试按钮后的截图：
![Screenshot_2024-06-14-15-36-17-599_cn dreamn qian](https://github.com/AutoAccountingOrg/Qianji_auto/assets/84030410/d00201ab-02d0-44de-972f-1f9759a496eb)

### 日志内容

[2024-06-14 15:34:58][自动记账:LogFragment]包名:com.wzn556.notifyme\n标题:默认通道\n主体通知通道测试消息

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/dreamncn/Qianji_auto/issues)，以确保该错误尚未被报告。

**Comment by AnkioTomas** [comment]
这好像是个已知的问题，虽然提交了修复代码，但是一直没有发新版本？时间太久忘了。
主要在于这一行的判断
https://github.com/AutoAccountingOrg/Qianji_auto/blob/dev/app/src/main/java/cn/dreamn/qianji_auto/bills/BillTools.java#L93

**Comment by LanYangYang-114** [comment]
> 这好像是个已知的问题，虽然提交了修复代码，但是一直没有发新版本？时间太久忘了。 主要在于这一行的判断 https://github.com/AutoAccountingOrg/Qianji_auto/blob/dev/app/src/main/java/cn/dreamn/qianji_auto/bills/BillTools.java#L93

我不会编译安卓应用，软件是旧仓库的release下载的🫢，看来要解决这个问题是只能自己编译代码了吗

**Comment by LanYangYang-114** [comment]
我尝试了一下从源码构建，出现了报错，可能是我用的版本太新导致的，如果方便的话，可以看一下如何解决吗，因为我不是很了解Android开发这些东西，万分感谢

```
FAILURE: Build completed with 3 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @a43f511

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':filechooser:processDebugAndroidTestManifest'.
> Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @a43f511

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':timepicker:processDebugAndroidTestManifest'.
> Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @a43f511

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 10s
123 actionable tasks: 5 executed, 118 up-to-date
```
