### ISSUE TITLE
微信无法获取支付消息

### ISSUE THREAD

**Issue by xia0ji233** [AutoAccountingOrg/Qianji_auto#3]
### 问题

如题，我的微信版本为 8.0.40 ，装了微x模块，自动记账版本为 3.3.4，微信不论是扫码，发红包还是转账，消息日志和数据日志均为空，已经给了root权限。

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/dreamncn/Qianji_auto/issues)，以确保该问题尚未被报告。

**Comment by CJYKK** [comment]
同样的问题，应该算bug了

**Comment by qaq112233** [comment]
+1

**Comment by lisidalange** [comment]
我支付宝微信都没有app日志

**Comment by AnkioTomas** [comment]
微信更新了消息格式导致的，该问题在4.0修复
