### ISSUE TITLE
钱迹4.0.5b6-896版本使用本模块时钱迹闪退

### ISSUE THREAD

**Issue by bryarrow** [AutoAccountingOrg/Qianji_auto#8]
### 当前使用的框架

- [X] Lsposed
- [ ] EdXposed
- [ ] 太极（无极）
- [ ] 轮回
- [ ] 梦境
- [ ] 其他虚拟框架

### 描述错误

钱迹4.0.5b6-896版本使用本模块时钱迹闪退

### 重现步骤

```bash
1.安装并激活模块
2.更新钱迹到4.0.5b6-896版本
3.打开钱迹界面
4.弹窗提示正在尝试适配，之后闪退
```

### 相关环境说明

自动记账版本：涅槃 3.3.7
钱迹版本：4.0.5b6-896
LSPosed版本：1.9.2 (7024)

### 日志内容

[2024-04-23 15:34:33][Xposed日志-Ankio-钱迹]钱迹 LeftSide.init Hook<com.mutangtech.qianji.ui.maindrawer.MainDrawerLayout.refreshAccount>
[2024-04-23 15:34:30][Xposed日志-Ankio-钱迹]钱迹版本：4.0.5b6(896)未适配，尝试适配！

### 这不是重复的 issue

- [x] 我已经搜索了[现有 issue](https://github.com/dreamncn/Qianji_auto/issues)，以确保该错误尚未被报告。

**Comment by AnkioTomas** [comment]
不要更新钱迹…尤其是测试版钱迹
—————————
Ankio 敬上
***@***.***
若无闲事挂心头，便是人间好时节。

**Comment by bryarrow** [comment]
钱迹更新了资产负债表功能……虽说现在是测试版，但之后总会正式上线的啊（挠头），这种有新功能的版本还是跟进一下比较好👉👈

**Comment by bryarrow** [comment]
这是hyperos给出的崩溃日志：
java.lang.LinkageError: Method void org.conscrypt.KitKatPlatformOpenSSLSocketImplAdapter.connect(java.net.SocketAddress) overrides final method in class Lcom/android/org/conscrypt/AbstractConscryptSocket; (declaration of 'org.conscrypt.KitKatPlatformOpenSSLSocketImplAdapter' appears in /data/app/~~WheTf4Z5EHXFEacOZ5FNdw==/com.mutangtech.qianji-zGlZYWQr5LEoyiglT2Z-2w==/base.apk!classes2.dex) at java.lang.VMClassLoader.findLoadedClass(Native Method) at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738) at java.lang.ClassLoader.loadClass(ClassLoader.java:363) at java.lang.ClassLoader.loadClass(ClassLoader.java:312) at cn.dreamn.qianji_auto.core.hook.hooks.qianji.Qianji.scan(Qianji.java:100) at cn.dreamn.qianji_auto.core.hook.hooks.qianji.Qianji.access$200(Qianji.java:52) at cn.dreamn.qianji_auto.core.hook.hooks.qianji.Qianji$1.run(Qianji.java:134)

**Comment by AnkioTomas** [comment]
1. 自动记账3.0不再更新，主要精力在自动记账4.0
2. 我不是全职搞自动记账，如果可以欢迎提交PR

—————————
Ankio 敬上
***@***.***
若无闲事挂心头，便是人间好时节。

**Comment by bryarrow** [comment]
好的，感谢。另外赞助进群的链接不能用了，麻烦更新一下，谢谢

**Comment by AnkioTomas** [comment]
暂时不受理入群请求哈
—————————
Ankio 敬上
***@***.***
若无闲事挂心头，便是人间好时节。
